import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Banner from '@/components/Banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Empowered Essence</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <p>The Transformation Technique Discovery Call</p>
        </div>
        <div>
          <p>I have tried as long as I can remember to gain control 
          over anxious intrusive thoughts</p> 
          <p>25 years of fighting with my mind, living on meds & still unable to function</p> 
          <p>Just as I was ready to give up, I was invited to observe an Aroma Freedom Technique Session Little did I realize using my sense of smell would give me a new lease on life</p>
          <p>Please...even if you don't feel like you have what it takes to try just one more time Your brains’ got this...trust the process</p>
          <p>Sincerely, Chelsea</p>
        </div>
        <div>
          <h2>Explore Your Potential</h2>
          <p>The part of our brain that handles our fight, flight, or freeze response also manages our sense of smell</p>
          <p>Using science & his experience with Essential Oils, Dr. Perkus designed the incredibly gentle Aroma Freedom Technique combined with the EO Blends that make it so highly effective</p>
          <p>(Memory Release Blend, Inner Child, Release, Transformation, Believe & Trauma Life EO's)</p>
          <p>Wouldn’t it make sense that using our dominant sense of smell would create quick & efficient results</p>
          <p>You sit back & enjoy the sweet scents of nature while your brain has a mini vacation</p>
        </div>
        <div>
          <h2>What is the Aroma Freedom Technique?</h2>
          <p>Benjamin Perkus is a renowned speaker & psychologist who utilizes essential oils and positive psychology to help people worldwide enact positive changes in their lives</p>
          <p>He holds a bachelor's degree in Philosophy and a doctorate in Clinical Psychology, and has taught internationally on topics such as trauma release, brain wellness, and personal fulfillment</p>
          <p>Dr. Perkus consults with individuals and institutions to improve quality of life through the use of essential oils and intentional focus</p>
          <p>lHe is the creator of the Aroma Freedom Technique certification course and practicum that has certified thousands of practitioners worldwide</p>
          <p>The technique highlights the powerful relationship between scent and emotion</p>
        </div>
        <div>
          <h2>For answers to FAQ check this video out</h2>
          [video]
        </div>
        <div>
          <h2>Privacy...</h2>
          <p>You don't have to share anything with me If you are a person that likes to share, that is ok too...</p>
          <p>The Aroma Freedom Technique (AFT) uses your sense of smell to gently shift awareness away from negative thoughts, feelings & memories</p>
          <p>This results in greater confidence & inner calm</p>
          <p>Each session combines the concepts of aromatherapy with psychology & neuroscience It is simple, gentle & effective in permanently shifting our negative thinking to positive</p>
        </div>
      </main>
    </>
  )
}
